services:
  rds-scanner:
    # build: .
    image: ghcr.io/minglarn/rds-scanner:latest
    container_name: rds-scanner
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "9000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - MQTT_BROKER=your_mqtt_broker_ip
      - MQTT_PORT=1883
      - MQTT_TOPIC_PREFIX=rds
